version: '3.8'

services:
  mysql:
    build: .
    container_name: mysql-invoice
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    networks:
      - devnet

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-invoice
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - devnet

networks:
  devnet:

volumes:
  jenkins_data: